// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MockGen.Templates.Setup
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MethodSetupPnTextTemplate : MethodSetupPnTextTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using MockGen.Matcher;\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing S" +
                    "ystem.Linq;\r\n\r\nnamespace MockGen.Setup\r\n{\r\n    internal abstract class MethodSet" +
                    "up");
            
            #line 13 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.GenericTypes));
            
            #line default
            #line hidden
            this.Write(" : MethodSetupBase, IMethodSetup");
            
            #line 13 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.GenericTypes));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 15 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 if (view.NumberOfTypes == 0) { 
            
            #line default
            #line hidden
            this.Write("        protected int numberOfCalls;\r\n");
            
            #line 17 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } else if (view.NumberOfTypes == 1) { 
            
            #line default
            #line hidden
            this.Write("        protected List<TParam1> calls = new List<TParam1>();\r\n");
            
            #line 19 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        protected List<(");
            
            #line 20 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.ParametersTypesWithName));
            
            #line default
            #line hidden
            this.Write(")> calls = new List<(");
            
            #line 20 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.ParametersTypesWithName));
            
            #line default
            #line hidden
            this.Write(")>();\r\n");
            
            #line 21 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        \r\n        protected new ActionConfiguration");
            
            #line 22 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.GenericTypes));
            
            #line default
            #line hidden
            this.Write(" currentConfiguration;\r\n\r\n");
            
            #line 24 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 if (view.NumberOfTypes == 0) { 
            
            #line default
            #line hidden
            this.Write("        internal MethodSetup()\r\n        {\r\n            currentConfiguration = new" +
                    " ActionConfiguration(base.currentConfiguration);\r\n        }\r\n");
            
            #line 29 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 if (view.NumberOfTypes > 0) { 
            
            #line default
            #line hidden
            this.Write("        protected void ForParameter(");
            
            #line 32 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.ConcatClassParameterByParameterType("Arg", "param")));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            ClearCurrentConfiguration();\r\n            currentConfig" +
                    "uration = new ActionConfiguration");
            
            #line 35 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.GenericTypes));
            
            #line default
            #line hidden
            this.Write("(base.currentConfiguration);\r\n");
            
            #line 36 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 foreach (var n in view.EnumerateNumbers) { 
            
            #line default
            #line hidden
            this.Write("            currentConfiguration.Matcher");
            
            #line 37 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(n));
            
            #line default
            #line hidden
            this.Write(" = ArgMatcher<TParam");
            
            #line 37 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(n));
            
            #line default
            #line hidden
            this.Write(">.Create(param");
            
            #line 37 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(n));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 38 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            \r\n        }\r\n\r\n");
            
            #line 41 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        public int NumberOfCalls \r\n        { \r\n            get \r\n            {\r\n " +
                    "               EnsureSpyingMethodsAreAllowed(nameof(NumberOfCalls));\r\n");
            
            #line 47 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 if (view.NumberOfTypes == 0) { 
            
            #line default
            #line hidden
            this.Write("                return numberOfCalls;\r\n");
            
            #line 49 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                return MatchingCalls.Count();\r\n");
            
            #line 51 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n        } \r\n\r\n");
            
            #line 55 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 if (view.NumberOfTypes > 0) { 
            
            #line default
            #line hidden
            
            #line 56 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 if (view.NumberOfTypes == 1) { 
            
            #line default
            #line hidden
            this.Write("        public IEnumerable");
            
            #line 57 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.GenericTypes));
            
            #line default
            #line hidden
            this.Write(" MatchingCalls\r\n");
            
            #line 58 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public IEnumerable<(");
            
            #line 59 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.ParametersTypesWithName));
            
            #line default
            #line hidden
            this.Write(")> MatchingCalls\r\n");
            
            #line 60 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            get\r\n            {\r\n                EnsureSpyingMethodsAre" +
                    "Allowed(nameof(MatchingCalls));\r\n");
            
            #line 65 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 if (view.NumberOfTypes == 1) { 
            
            #line default
            #line hidden
            this.Write("                return calls.Where(@params => currentConfiguration.Match(@params)" +
                    ");\r\n");
            
            #line 67 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                return calls.Where(@params => currentConfiguration.Match(");
            
            #line 68 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.ConcatParameters("@params.param")));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 69 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n\r\n");
            
            #line 73 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        public void Execute(Action");
            
            #line 74 "D:\Dev\MockGen\src\MockGen\Templates\Setup\MethodSetupPnTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(view.GenericTypes));
            
            #line default
            #line hidden
            this.Write(" callback)\r\n        {\r\n            EnsureConfigurationMethodsAreAllowed(nameof(Ex" +
                    "ecute));\r\n            currentConfiguration.ExecuteAction = callback;\r\n        }\r" +
                    "\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class MethodSetupPnTextTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
